### ISSUE TITLE
Suggestion: Allow specifying users to ignore in the settings file

### ISSUE THREAD

**Issue by louis6321** [CataIana/twitch-modlogging#1]
It would be nice if I could specify users to ignore in the settings file. I have some channels with significant bot modding activity and I only care about logging human actions, so I would specify the users (like ohbot, moobot, etc.) to ignore.

I'm thinking the ignored users would be global for the whole bot rather than specified per channel, but either way works I guess.
I would just spin up a second instance of the bot so I'd have one that logs everything and one that doesn't log specified users.

**Comment by CataIana** [comment]
Added this as a global config option, will be available soon
