### ISSUE TITLE
Adding VIPs via Twitch Chat and IRC Clients is currently bugged

### ISSUE THREAD

**Issue by ghost** [CataIana/twitch-modlogging#3]
Looks like Twitch has changed a mod action yet again. Adding VIPs via Native Chat presents a safety embed, adding via Chatty presents both the safety embed and the actual intended vip action embed (I guess it sends twice now, for some reason?)

![image](https://user-images.githubusercontent.com/48177804/118303504-a327f400-b539-11eb-8175-286f0b977f95.png)

**Comment by CataIana** [comment]
Thanks, issue has been solved, until twitch changes it again :)
