### ISSUE TITLE
When connection is lost, reconnecting fails and doesn't try again

### ISSUE THREAD

**Issue by NaJager** [CataIana/twitch-modlogging#5]
Had this happen a few times, works perfectly fine again when I restart the systemd service the bot is running in: 
```2022-02-15 06:11:03PM INFO [main main 128]: Connected to websocket
2022-02-15 07:16:28PM WARNING [main messagehandler 181]: Reconnecting...
2022-02-15 07:16:33PM WARNING [main message_reciever 145]: Connection with server closed
2022-02-15 07:17:03PM WARNING [main heartbeat 157]: Connection with server closed
```
After which it keeps running and doesn't succeed, so the systemd service doesn't restart automatically, but the bot doesn't attempt to reconnect either

**Comment by CataIana** [comment]
It never reconnects because the worker task doesn't die when the connection closes. This worked fine before I added the worker task because the other two would die when the connection was closed

**Comment by CataIana** [comment]
But it should be fixed now :)
