### ISSUE TITLE
Feature Request: Uptime Robot Heartbeat Support

### ISSUE THREAD

**Issue by louis6321** [CataIana/twitch-modlogging#6]
I would be cool if the bot could send a POST or GET request to an Uptime Robot endpoint every X minutes (endpoint and frequency would be configured in the settings file) so if it dies (usually due to expired Twitch oauth) I can be notified.

More info: https://blog.uptimerobot.com/new-feature-heartbeat-monitoring/

**Comment by CataIana** [comment]
Sounds good, I've added it. I don't have uptime robot to actually test it, so I'll leave this open until it can be confirmed it works

**Comment by louis6321** [comment]
Working perfectly, many thanks!
